In [22]:
import pandas as pd 
import plotly.express as px 
import seaborn as sns 
import numpy as np
import datetime as dtt
from datetime import date
from datetime import datetime

In [12]:
from dash import Dash, dcc, html, Input, Output, State
import dash_bootstrap_components as dbc
import plotly.express as px
from dash import Dash, dash_table
import dash_table_experiments as dt

In [26]:
back_test_bull = pd.read_csv("back_test_bull_final6.csv")
back_test_bull['date'] = pd.to_datetime(back_test_bull['date'])
back_test_bull['date1'] = back_test_bull['date'].dt.date
bull = back_test_bull.set_index("date1")

                          date          100  Percent Change       date1
6183 2022-10-17 11:05:00+05:30  1193.859280       -0.054589  2022-10-17
6184 2022-10-17 13:40:00+05:30  1194.563858        0.059017  2022-10-17
6185 2022-10-17 14:25:00+05:30  1194.623993        0.005034  2022-10-17
6186 2022-10-17 14:50:00+05:30  1195.271983        0.054242  2022-10-17
6187 2022-10-18 10:10:00+05:30  1195.980451        0.059273  2022-10-18
6188 2022-10-18 10:55:00+05:30  1196.206324        0.018886  2022-10-18

In [46]:
back_test_bull[back_test_bull['date1'] >= dtt.date(2020,1,1)]

                          date          100  Percent Change       date1
3790 2020-01-01 11:55:00+05:30   368.605856        0.003860  2020-01-01
3791 2020-01-01 12:40:00+05:30   369.400626        0.215615  2020-01-01
3792 2020-01-01 13:45:00+05:30   369.567293        0.045118  2020-01-01
3793 2020-01-01 14:35:00+05:30   369.450983       -0.031472  2020-01-01
3794 2020-01-01 15:15:00+05:30   369.705272        0.068829  2020-01-01
...                        ...          ...             ...         ...
6184 2022-10-17 13:40:00+05:30  1194.563858        0.059017  2022-10-17
6185 2022-10-17 14:25:00+05:30  1194.623993        0.005034  2022-10-17
6186 2022-10-17 14:50:00+05:30  1195.271983        0.054242  2022-10-17
6187 2022-10-18 10:10:00+05:30  1195.980451        0.059273  2022-10-18
6188 2022-10-18 10:55:00+05:30  1196.206324        0.018886  2022-10-18

[2399 rows x 4 columns]

In [47]:
# app = Dash(external_stylesheets=[dbc.themes.CYBORG])

# app.layout = html.Div([
#     dbc.Row([
#         dbc.Col([
#             # dcc.Input(id = 'pr', type= 'number'),
#             dcc.DatePickerSingle(
#             id='date1',
#             min_date_allowed=date(2015, 8, 5),
#             max_date_allowed=date(2022, 9, 19),
#             initial_visible_month=date(2017, 8, 5),
#             date=date(2017, 8, 25)
#     )
#         ], width=3),
#         dbc.Col([
#             dcc.Graph(id = 'capital', figure ={})
#         ], width=9)
#     ])
# ])

# @app.callback(
#     Output("capital", "figure"),
#     # [Input("pr", "value"),
#     Input("date1", "d1"))
#     # Input("date1", "d2")
    

# def trial(d1):

#     if d1 :
#         d1 = datetime.strptime(d1, "%Y-%m-%d").strftime('%#d/%#m/%#Y')
#         # d2 = datetime.strptime(d2, "%Y-%m-%d").strftime('%#m/%#d/%#Y')
#         bull2 = back_test_bull[(back_test_bull['date1'] >= d1)]

#         # interest = ["Initial Capital"]
#         # date = ['-']
#         # for i in bull2['Percent Change']:
#         #     interest.append(i)
#         # for i in bull2['date1']:
#         #     date.append(i)
#         # #interest = back_test['Percent Change']
#         # capital = [pr]
#         # for i in range(1,len(interest)):
#         #     for j in range(len(capital)):
#         #         if i  == (j + 1):
#         #             t = (interest[i]*capital[j])/100 + capital[j]
#         #             capital.append(t)
#         # a = pd.DataFrame({"date": date, "Interest Rates" : interest,"Capital": capital})



#         fig = px.line(bull2, x = bull2['date1'], y = bull2['Percent Change'])
#         return fig
#     else:
#         Dash.no_update()

# app.run_server(debug = False, port= 5050)

In [50]:
app = Dash(external_stylesheets=[dbc.themes.CYBORG])
app.layout = html.Div([
    dbc.Row([
        dcc.DatePickerSingle(
            id='date1',
            min_date_allowed=date(2015, 8, 5),
            max_date_allowed=date(2022, 9, 19),
            initial_visible_month=date(2017, 8, 5),
            date=date(2017, 8, 25)),
        dcc.Graph(id= 'g', figure={})]
    )
])
@app.callback(
    Output('g', 'figure'),
    Input('date','val1')
)
def func(val1):
    if val1:
        d1 = datetime.strptime(val1, "%Y-%m-%d").strftime('%#d/%#m/%#Y')

        b = back_test_bull[back_test_bull['date1']>= d1]
        fig = px.line(b, x=b['date1'], y=b['Percent Change'])
        return fig
    else:
        Dash.no_update()
app.run_server(debug = False)

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app '__main__' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off